### ISSUE TITLE
NoClassDefFoundError on s3 upload

### ISSUE THREAD

**Issue by PalashBansal96** [gonzadocarmo/teamcity-s3-plugin#12]
**Describe the bug**
When trying to upload some artifacts to S3 from Teamcity, getting the error:
```java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.amazonaws.util.Base64.encodeAsString(Base64.java:39)
	at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1438)
	at com.dcn.teamcity.awsS3Plugin.adapters.AWSS3UploadAdapter.uploadToBucket(AWSS3UploadAdapter.java:30)
	at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.uploadFile(AWSS3BuildProcessAdapter.java:174)
	at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.uploadFilesToBucket(AWSS3BuildProcessAdapter.java:136)
	at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.runProcess(AWSS3BuildProcessAdapter.java:104)
	at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.start(AWSS3BuildProcessAdapter.java:88)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:79)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:312)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:275)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Class 'javax.xml.bind.DatatypeConverter' was not found
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:85)
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:40)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 more
[11:19:05][Upload to S3 bucket: brands.mouve.app] Failed to start build runner 'awsS3Plugin'
[11:19:06][Upload to S3 bucket: brands.mouve.app] Step Amazon S3 Uploader failed with unexpected error
```

**Additional context**
TeamCity Professional 2019.2.2 (build 71923)
teamcity-s3-plugin v0.1.2

**Comment by sevanmarc** [comment]
I get the same thing on TeamCity 2020.1. Machine is a clean install of windows server 2019, the only thing installed is MS build tools 2019 and TeamCity 2020.1

**Comment by kinguru** [comment]
same for me
![image](https://user-images.githubusercontent.com/54497/89963024-2638b880-dc4f-11ea-9d63-ada93817d2be.png)

**Comment by gonzadocarmo** [comment]
@kinguru , Could you please give it a try at this rc version: https://github.com/gonzadocarmo/teamcity-s3-plugin/releases/tag/v0.1.3-rc ?

**Comment by kinguru** [comment]
Can't check right now, will schedule for next month. I'm using integrated plugin now, but it don't allow to select artifact storage per build configuration.
