### ISSUE TITLE
 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter on clean TC 2020.1 installation

### ISSUE THREAD

**Issue by sevanmarc** [gonzadocarmo/teamcity-s3-plugin#13]
New windows server 2019, the only thing installed is MS build tools 2019 and TeamCity 2020.1

When build gets to this plugin it fails with the following error:

Transferring [C:\TeamCity\buildAgent\work\d1df6864f98d2599\<BuildName>\AWSSDK.CloudWatch.dll] to <ProjectFolder>
06:08:26
    java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
  at com.amazonaws.util.Base64.encodeAsString(Base64.java:39)
  at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
  at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1438)
  at com.dcn.teamcity.awsS3Plugin.adapters.AWSS3UploadAdapter.uploadToBucket(AWSS3UploadAdapter.java:30)
  at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.uploadFile(AWSS3BuildProcessAdapter.java:174)
  at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.uploadFilesToBucket(AWSS3BuildProcessAdapter.java:136)
  at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.runProcess(AWSS3BuildProcessAdapter.java:104)
  at com.dcn.teamcity.awsS3Plugin.AWSS3BuildProcessAdapter.start(AWSS3BuildProcessAdapter.java:88)
  at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:58)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
 at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
 at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:79)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:313)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:56)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:276)
  at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by sevanmarc** [comment]
Duplicate of #12
